### ISSUE TITLE
Bucket Not Found and Key Missing Errors in Custom Build Process

### ISSUE THREAD

**Issue by JuarezCulau** [aws-solutions/enhanced-document-understanding-on-aws#19]
**Describe the bug**

It's probably not a bug, more like I did not understand the documentation clearly, and it's causing this problem. I'm not a cloud developer, but I'm trying to make a few modifications to deploy a specific application. Right now, the code has no modifications at all; I am just trying to deploy a custom build following the steps in the docs, but I am getting errors (bucket not found, key missing) while trying to set the buckets for the custom build.

**To Reproduce**

Basically, I created two S3 buckets for DIST_OUTPUT_BUCKET and CF_TEMPLATE_BUCKET_NAME. The name format for DIST_OUTPUT_BUCKET included the region, as described in the parameters details, like this: my-bucket-us-east-1. CF_TEMPLATE_BUCKET_NAME had a random bucket name without the region in the name itself.

If I understood correctly, the global-s3-assets must be uploaded to CF_TEMPLATE_BUCKET, and the regional-s3-assets to the DIST_OUTPUT_BUCKET. I did that after building the distributable with these buckets. However, when deploying on CloudFormation, I get an error saying a bucket was not found.

By not changing the name my-bucket-us-east-1 but giving the name without the region part to the variable DIST_OUTPUT_BUCKET, like this: my-bucket, the bucket is not missing anymore. So, I am assuming we should give the name of the bucket till the region part of the name but still create a bucket with the region in the name, right?

Anyways, I still get an error saying a key is missing from the S3 bucket. I'm not sure which one. So just to make sure, I uploaded all global and regional assets to both buckets, but the same error persists.

**Expected behavior**

Custom build with no modifications to be deployed. 

**Please complete the following information about the solution:**

- [ ] Version: v1.0.3

- [ ] Region: us-east-1
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? 
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? Nothing in the logs

**Additional context**

I am using Cloud9 (Amazon Linux) and deploying directly on Cloud Formation though AWS interface.

**Comment by knihit** [comment]
@JuarezCulau , sorry to hear you are facing issues when trying to deploy. Have you tried the first option: `using cdk deploy` to see if it works?.

For option 2, `Creating a custom build`, are you deploying in the same account/ region where the buckets have been created. I think making the buckets `public read` might solve the problem.

**Comment by JuarezCulau** [comment]
@knihit Thank you for your suggestions. Using cdk deploy works great if it's not a custom build. If I use cdk deploy with a custom build, I encounter a different error during deployment. Instead of not finding a key file in the bucket, I receive an access denied error to the bucket. I have the necessary permissions to access and retrieve data from the buckets. Additionally, I noticed a warning during deployment that I believe might be related to this issue. It essentially states that the current credentials could not be used to assume a file-publishing-role but proceeds anyway.

Regarding the account/region, it’s the same. I may have misunderstood something in the build process. Are the steps I mentioned in the "To Reproduce" topic correct?

**Comment by knihit** [comment]
@JuarezCulau , I am not sure why you say its not a custom build. You can still customize the code and perform `cdk deploy`. Do you have a requirement to distribute it to another team. If you are deploying in your AWS account, IMO, the `cdk deploy` option should work for you.

For the error you mentioned `access denied error to the bucket`, have you run `cdk bootstrap`. When it states `current credentials could not be used to assume a file-publishing-role` can you provide details on what role you are currently using. Are you using a higher privilege role to deploy. If its your own account, I would suggest assuming an `Adminstrator` role to deploy the template. You can also specify `cdk deploy --role-arn arn:aws:iam::01234567890:role/<role-with-adminstrator-access>` to supply CloudFormation with an elevated role.

Me and my team uses `cdk deploy` during our development and we make modifications and keep deploying updates. I have not seen this error before with `cdk deploy`. Hence my hunch is that is probably due to the IAM policies that are associated with the user/ role you are using. Those don't have sufficient permissions.

**Comment by JuarezCulau** [comment]
Thanks for the information, I managed to make it work now.

**Comment by knihit** [comment]
@JuarezCulau thank you for letting us know. Just so that our team builds on troubleshooting guide, if you are comfortable sharing the root cause and final resolution which made it work.

**Comment by JuarezCulau** [comment]
@knihit It is actually very simple, I just didn’t know I had to bootstrap before deploying in CDK. Thanks for the info. I still can’t use the second option to use CloudFormation templates, but there is no need for me anymore since deploying with CDK is working.
