### ISSUE TITLE
Removal of User Authentication for custom API build - Cognito

### ISSUE THREAD

**Issue by Komal-99** [aws-solutions/enhanced-document-understanding-on-aws#30]
Hi, 

I was deploying the service for custom build and need to remove the user authentication, cannot find a fix for that.
Anyone could help in disabling the cognito service to direct access the api for custom use case.

**Comment by knihit** [comment]
Hello @Komal-99 , thank you for reaching out. We have not tested this completely. But to start with there are few things you can do

1. Remove this [line](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/main/source/ui/src/App.js#L171). This is a amplify authentication decorator.
2. On the ApiGateway remove the following [line](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/main/source/infrastructure/lib/api/rest-endpoint.ts#L496).

If these dont work, you can try removing request header for Authorization token [as on this line](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/main/source/infrastructure/lib/api/rest-endpoint.ts#L265). IMO, this change is not required, but if request validation fails, you may need to remove it.

Let us know if you face any issues.

**Comment by Komal-99** [comment]
Just to make sure , I Have followed 
![image](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/assets/74819092/5a360c51-cda8-49c5-8cf4-216be38fdfc0)
this and updated mappings and then deployed it. I successfully got an API url but when I try to hit POST request from postman on that url to create ```case``` it returns a 403 error as message: forbidden. 

So I am Guessing this is auth error as if we use it with UI, we need to first signup or login but from Postman I am directly making a request to create new case. 

Do clarify me If I am thinking in a wrong direction.

**Comment by knihit** [comment]
Yes the API requires an Auth token header, generated by the Cognito service.  You have 2 options,

1. if you want to remove the API Authorizaation, you can do so from AWS Console, navigating to ApiGateway, look up for Authorizer and delete the underlying configuration.
2. You can generate the id token. Refer this [link](https://repost.aws/questions/QUW-FCbWmbRSSRQnfgQEdefg/how-do-i-obtain-an-id-token-from-cognito-without-hosted-ui).

If you are not looking to remove Auth permanently and only need to bypass for testing, I would suggest go with option 2.

**Note**: you can also test the API from the AWS console under ApiGateway. This way you would not require any authentication.

**Comment by Komal-99** [comment]
Yes, as my project already have user authentication , I need to remove this auth and directly hit the api

**Comment by knihit** [comment]
As a security best practice, you should have APIs protected with Authentication. Instead of using Cognito, if you have a different authentication provider, you can configure a custom authorizer and integrate it with ApiGateway. An ApiGateway endpoint is a public endpoint, unless you make it private [link](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-private-apis.html). For public endpoints anyone with information about the URL would be able to execute a GET/ POST request. So my suggestion would be to review your architecture from a security lens, for the need to have authentication for APIs too.

**Comment by knihit** [comment]
For security reasons, we cannot add a feature to remove Authentication. Hence will be closing the ticket. If you have any further questions. Feel free to re-open this ticket or create a new one.

**Comment by Komal-99** [comment]
No need to add a feature for removing authentication, the concern of this ticket was only to understand where we can tweak things as per our needs. and yes agree on the security concern, can you provide more details to configure the custom authorizer? For ex- I have Google auth when a user login on to my website and after that he is directed to the dashboard where he can perform operations out of them one will be to upload the documents and get text extraction done to get formated results and To make sure that only authenticated user who has access to my website can hit API.

**Comment by knihit** [comment]
You can configure Cognito with OAuth2.0 flow. Few changes to be made:
1. The App.js would look similar to the following [link](https://github.com/aws-solutions/network-orchestration-for-aws-transit-gateway/blob/main/source/ui/src/App.tsx). This is from another solution.
2. In the account/ region where the solution is deployed, there would be a Cognito User Pool. This pool's configuration would need to be changed as [here](https://docs.aws.amazon.com/cognito/latest/developerguide/google.html)

**Comment by LakshyaN15** [comment]
Hi!
The above template is the template we used on cloudformation. Under the **Mappings** section we configured RedactionWorkflow, CustomDashboard and WebApp as "No". Now we just want to call the API and we have removed the authorizers. Again, it gives Status Code 403: Forbidden.

Kindly Help!

![Screenshot 2024-03-20 134233](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/assets/25548101/babfd66e-e9e7-4697-ac30-96598432ac52)
![Screenshot 2024-03-20 134149](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/assets/25548101/d25dad00-a537-41a7-987a-f1811aa75807)

**Comment by Komal-99** [comment]
Hi, We are not able to Fix the issue as of now. We have changed AuthorizationType from "COGNITO_USER_POOLS" to "NONE" and remove  AuthorizerId key wherever specified in Mappings template.
![image](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/assets/74819092/3870ee5d-b72e-49b0-9d77-8e192b288b14)
But still when deploying it creates a User.
![image](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/assets/74819092/d19471a3-4068-4a4f-a5d6-f697bc98d3c0)
 and shows this error at API URL and from postman passing {'caseName':"TEST"} giving 403 forbidden error.
![image](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/assets/74819092/d16354fb-2eeb-4711-a0ee-3756259049bf)
@knihit  Please help us we are unable to understand out mistake.

**Comment by knihit** [comment]
There should a lambda function by the name`requestprocessor`. Can you please check the logs. We pass the auth token to the lambda to extract the user. So when I tried removing the authorizer from ApiGW, I can see the request going to the lambda function, but it errors out because it expects a token

```
    at jwtDecode (/opt/nodejs/node_modules/common-node-lib/node_modules/jwt-decode/build/cjs/index.js:40:15)
    at exports.decodeJwtToken (/opt/nodejs/node_modules/common-node-lib/cognito/decode-jwt-token.js:25:16)
    at exports.getUserIdFromEvent (/opt/nodejs/node_modules/common-node-lib/cognito/decode-jwt-token.js:38:29)
    at exports.handler (/var/task/index.js:50:38)
```

Now you can remove the call to check the access token and retrieve the userId. An example of this call is [here](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/main/source/lambda/fetch-records/index.js#L50C38-L50C56), but you are going into uncharted territory. The DynamoDB table design also takes into account the user information. Also note that anything which says `SharedLib` is under the `lambda/layers/common-node-lib` folder. IMO, using Federated sign-in would still be the easier option rather than removing Authentication.

**Note**: The application is designed to be `user aware`. It has to know if a `user information` was supplied as it is using that process to cases/ documents. If you remove Auth, you would somehow need to get a user dynamically or make it static.

**Comment by knihit** [comment]
Note that I close the issue, but you want to continue on this thread, please consider re-opening the ticket or creating a new issue.

**Comment by knihit** [comment]
In the UI, you would also need to change the following [line](https://github.com/aws-solutions/enhanced-document-understanding-on-aws/blob/main/source/ui/src/App.js#L171) to 

```
export default App
```

basically removing the `withAuthenticator` call.
